#!/usr/bin/env bash
# Build and test against the real iOS SDK.
#
# A macOS `swift build` is NOT a sufficient gate. It cannot see the feature
# module at all — VueApp is iOS-only — and it has already missed one class of
# failure the iOS build catches outright, App Intents metadata generation.
#
# DEVELOPER_DIR rather than `sudo xcode-select -s`, so this needs no password.
set -euo pipefail

export DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
SCHEME="VueLights"

cd "$(dirname "$0")/.."

echo "▸ Generating the project"
xcodegen generate

# Pick a simulator that exists rather than naming one and hoping. A hardcoded
# "iPhone 17" is right on one laptop and wrong on a CI runner, whose image ships
# whatever Apple shipped that month.
#
# Selected by UDID, not by name: `simctl` prints `<name> (<udid>) (<state>)` and
# a name can itself contain brackets — "iPhone SE (3rd generation)" — so cutting
# at the first "(" asks for a device that exists nowhere.
DESTINATION="${SIM:+platform=iOS Simulator,name=$SIM}"
if [ -z "$DESTINATION" ]; then
  sim_line="$(xcrun simctl list devices available \
    | grep -E '^ +iPhone .*\([0-9A-Fa-f-]{36}\)' | tail -1)"
  [ -n "$sim_line" ] || { echo "no iPhone simulator available" >&2; exit 1; }
  sim_id="$(printf '%s' "$sim_line" | grep -oE '[0-9A-Fa-f-]{36}' | head -1)"
  sim_name="$(printf '%s' "$sim_line" | sed -E 's/ \([0-9A-Fa-f-]{36}\).*$//; s/^ +//; s/ +$//')"
  DESTINATION="platform=iOS Simulator,id=$sim_id"
  echo "▸ Simulator: $sim_name"
else
  echo "▸ Simulator: $SIM (from SIM)"
fi

echo "▸ Building $SCHEME"
xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -quiet build

# Siri, or the silence that looks exactly like it.
#
# Two ways this feature dies without failing a build, both of them silent:
#
#  1. `AppShortcutsProvider` conformances are only extracted from the target
#     being BUILT. With `VueShortcuts` in a package target — which is where it
#     lived, and where it looks like it belongs — everything compiles, archives,
#     uploads and installs, `appintentsnltrainingprocessor` mentions "No
#     AppShortcuts found - Skipping" in passing, and the app answers to nothing.
#  2. A phrase without `\(.applicationName)` compiles and simply never matches.
#
# Checked against the built ARTIFACT rather than against the build log: the SSU
# training phase does not re-run on an incremental build, so a log grep passes
# on a clean build and fails on the next one for no reason at all.
echo "▸ Checking Siri phrases survived the build"
PRODUCTS_DIR="$(xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" \
  -showBuildSettings 2>/dev/null | grep -m1 '  BUILT_PRODUCTS_DIR' | sed 's/.*= //')"
ACTIONS="$PRODUCTS_DIR/$SCHEME.app/Metadata.appintents/extract.actionsdata"
[ -f "$ACTIONS" ] || { echo "no App Intents metadata at $ACTIONS" >&2; exit 1; }

python3 - "$ACTIONS" <<'PY'
import json, sys

data = json.load(open(sys.argv[1]))
shortcuts = data.get("autoShortcuts", [])
if not shortcuts:
    sys.exit(
        "✗ No App Shortcuts in the built app — Siri would be silently dead.\n"
        "  VueShortcuts must live in the APP target (App/Sources), never in a\n"
        "  package target. See App/Sources/VueShortcuts.swift.")

bad = [
    (s["actionIdentifier"], p["key"])
    for s in shortcuts
    for p in s.get("phraseTemplates", [])
    if "${applicationName}" not in p["key"]
]
for action, phrase in bad:
    print(f'✗ {action}: "{phrase}" never names the app, so it will never match.')
if bad:
    sys.exit(1)

# Both ceilings are counted expansively by the system; these are the compile-time
# halves of them. Phrase templates multiply by entity values at runtime.
if len(shortcuts) > 10:
    sys.exit(f"✗ {len(shortcuts)} App Shortcuts — the limit is 10.")

phrases = sum(len(s.get("phraseTemplates", [])) for s in shortcuts)
print(f"  · {len(shortcuts)}/10 App Shortcuts, {phrases} phrase templates, all naming the app")
PY

# Per test target, NOT the app scheme. `xcodebuild -scheme VueLights test` fails
# with "not currently configured for the test action": the app target is
# generated by XcodeGen and the tests belong to the Swift package, so they
# surface as their own schemes. Running the app scheme here would report a
# problem before it ever ran a test, which means nothing would be verified.
echo "▸ Testing"
for suite in VueCoreTests VueRepositoriesTests VueIntentsTests; do
  echo "  · $suite"
  xcodebuild -scheme "$suite" -destination "$DESTINATION" -quiet test
done

echo "✓ iOS build and tests passed"
