#!/usr/bin/env bash
# Build and test against the real iOS SDK.
#
# A macOS `swift build` is NOT a sufficient gate. It cannot see the feature
# module at all — VueApp is iOS-only — and it has already missed one class of
# failure the iOS build catches outright, App Intents metadata generation.
#
# DEVELOPER_DIR rather than `sudo xcode-select -s`, so this needs no password.
set -euo pipefail

export DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
SCHEME="VueLights"

cd "$(dirname "$0")/.."

echo "▸ Generating the project"
xcodegen generate

# Pick a simulator that exists rather than naming one and hoping. A hardcoded
# "iPhone 17" is right on one laptop and wrong on a CI runner, whose image ships
# whatever Apple shipped that month.
#
# Selected by UDID, not by name: `simctl` prints `<name> (<udid>) (<state>)` and
# a name can itself contain brackets — "iPhone SE (3rd generation)" — so cutting
# at the first "(" asks for a device that exists nowhere.
DESTINATION="${SIM:+platform=iOS Simulator,name=$SIM}"
if [ -z "$DESTINATION" ]; then
  sim_line="$(xcrun simctl list devices available \
    | grep -E '^ +iPhone .*\([0-9A-Fa-f-]{36}\)' | tail -1)"
  [ -n "$sim_line" ] || { echo "no iPhone simulator available" >&2; exit 1; }
  sim_id="$(printf '%s' "$sim_line" | grep -oE '[0-9A-Fa-f-]{36}' | head -1)"
  sim_name="$(printf '%s' "$sim_line" | sed -E 's/ \([0-9A-Fa-f-]{36}\).*$//; s/^ +//; s/ +$//')"
  DESTINATION="platform=iOS Simulator,id=$sim_id"
  echo "▸ Simulator: $sim_name"
else
  echo "▸ Simulator: $SIM (from SIM)"
fi

echo "▸ Building $SCHEME"
xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -quiet build

# Per test target, NOT the app scheme. `xcodebuild -scheme VueLights test` fails
# with "not currently configured for the test action": the app target is
# generated by XcodeGen and the tests belong to the Swift package, so they
# surface as their own schemes. Running the app scheme here would report a
# problem before it ever ran a test, which means nothing would be verified.
echo "▸ Testing"
for suite in VueCoreTests VueRepositoriesTests; do
  echo "  · $suite"
  xcodebuild -scheme "$suite" -destination "$DESTINATION" -quiet test
done

echo "✓ iOS build and tests passed"
